# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'userbaseInfo_1.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QByteArray
from PyQt5.QtGui import QPixmap
from PyQt5.QtWidgets import QWidget, QLabel


class BaseInfo(QWidget):

    def __init__(self,info, parent=None):
        super(BaseInfo, self).__init__(parent)
        self.setupUi(info)

    def setupUi(self, info):
        self.label = QtWidgets.QLabel(self)
        self.label.setGeometry(QtCore.QRect(80, 30, 72, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self)
        self.label_2.setGeometry(QtCore.QRect(80, 80, 72, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self)
        self.label_3.setGeometry(QtCore.QRect(80, 130, 72, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self)
        self.label_4.setGeometry(QtCore.QRect(80, 180, 72, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self)
        self.label_5.setGeometry(QtCore.QRect(80, 230, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self)
        self.label_6.setGeometry(QtCore.QRect(80, 280, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self)
        self.label_7.setGeometry(QtCore.QRect(80, 330, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self)
        self.label_8.setGeometry(QtCore.QRect(220, 30, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self)
        self.label_9.setGeometry(QtCore.QRect(220, 80, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self)
        self.label_10.setGeometry(QtCore.QRect(220, 130, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self)
        self.label_11.setGeometry(QtCore.QRect(220, 180, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self)
        self.label_12.setGeometry(QtCore.QRect(220, 230, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self)
        self.label_13.setGeometry(QtCore.QRect(220, 280, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self)
        self.label_14.setGeometry(QtCore.QRect(220, 330, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.imageView = QLabel(self)
        self.imageView.setGeometry(QtCore.QRect(420, 230, 221, 171))
        self.imageView.setObjectName("imageView")
        self.label_15 = QtWidgets.QLabel(self)
        self.label_15.setGeometry(QtCore.QRect(470, 200, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self)
        self.label_16.setGeometry(QtCore.QRect(480, 10, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.imageView_2 = QLabel(self)
        self.imageView_2.setGeometry(QtCore.QRect(420, 40, 161, 141))
        self.imageView_2.setObjectName("graphicsView_2")

        self.retranslateUi(info,self)
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self,info, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "用户名："))
        self.label_2.setText(_translate("Form", "姓名："))
        self.label_3.setText(_translate("Form", "性别："))
        self.label_4.setText(_translate("Form", "年龄："))
        self.label_5.setText(_translate("Form", "出生年月："))
        self.label_6.setText(_translate("Form", "身份证号："))
        self.label_7.setText(_translate("Form", "家庭住址："))
        self.label_8.setText(_translate("Form", info['username']))
        self.label_9.setText(_translate("Form", info['name']))
        self.label_10.setText(_translate("Form", info['sex']))
        self.label_11.setText(_translate("Form", info['age']))
        self.label_12.setText(_translate("Form", info['birth']))
        self.label_13.setText(_translate("Form", info['ID']))
        self.label_14.setText(_translate("Form", info['home_addr']))
        ima_bytearray = QByteArray.fromBase64(info['icon_head'].encode('utf8'))
        image = QPixmap()
        image.loadFromData(ima_bytearray)
        image = image.scaled(self.imageView.width(), self.imageView.height())
        self.imageView.setPixmap(image)
        ima_bytearray = QByteArray.fromBase64(info['user_head'].encode('utf8'))
        image = QPixmap()
        image.loadFromData(ima_bytearray)
        image = image.scaled(self.imageView_2.width(), self.imageView_2.height())
        self.imageView_2.setPixmap(image)

        self.label_15.setText(_translate("Form", "手持身份证"))
        self.label_16.setText(_translate("Form", "头像"))

